# Site settings
title: We Are VA
email: nik@thevariousartists.coma.u
description: > # this means to ignore newlines until "baseurl:"
  New VA Website
baseurl: ''

# Build settings
markdown: kramdown

permalink: pretty

exclude:
  - package.json
  - node_modules
  - gulpfile.js

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
