title: The Various Artists
short_title: weareva
description: static site - booooom!
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
collections:
  people:
    output: true
    permalink: "/about/:path/"
  work:
    output: true
    permalink: "/work/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
gems:
  - jekyll-menus
  - jekyll-feed
